/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppAside: typeof import('./src/components/layout/AppAside.vue')['default']
    AppConfig: typeof import('./src/components/layout/AppConfig.vue')['default']
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppTopbar: typeof import('./src/components/layout/AppTopbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Calendar: typeof import('primevue/calendar')['default']
    Card: typeof import('./src/components/common/Card.vue')['default']
    Chart: typeof import('primevue/chart')['default']
    CreateQuoteView: typeof import('./src/components/quotes/create/CreateQuoteView.vue')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    IconField: typeof import('primevue/iconfield')['default']
    InputIcon: typeof import('primevue/inputicon')['default']
    Menu: typeof import('primevue/menu')['default']
    QuotesOverviewWidget: typeof import('./src/components/dashboard/QuotesOverviewWidget.vue')['default']
    QuotesTableView: typeof import('./src/components/quotes/QuotesTableView.vue')['default']
    QuotesView: typeof import('./src/components/quotes/QuotesView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsWidget: typeof import('./src/components/dashboard/StatsWidget.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
